name: 'Github Agent'
description: 'Run an LLM agent in response to GitHub events, with mustache-templated instructions.'
author: 'blevinstein'
inputs:
  instructions:
    description: 'Path to a file (e.g., file://fix-issue.txt) or inline string with instructions. Supports mustache.js templating with event context.'
    required: true
  model:
    description: 'LLM model to use.'
    required: true
  system_prompt:
    description: 'System prompt to send as a system message before the user message.'
    required: false
  treat_reply_as_comment:
    description: "If true, post the agent's text response as a comment on the triggering issue or PR."
    required: false
    default: 'false'
  mcp_servers:
    description: 'JSON string or file:// path specifying additional MCP server configs to use (optional). Example: |\n  {\n    "time": {\n      "type": "stdio",\n      "command": "docker",\n      "args": ["run", "-i", "--rm", "mcp/time"]\n    }\n  }'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'zap'
  color: 'blue' 