name: 'blevinstein-github-agent'
description: 'Run an LLM agent in response to GitHub events, with mustache-templated instructions.'
author: 'blevinstein'
inputs:
  instructions:
    description: 'Path to a file (e.g., file://fix-issue.txt) or inline string with instructions. Supports mustache.js templating with event context.'
    required: true
  model:
    description: 'LLM model to use.'
    required: true
  system_prompt:
    description: 'System prompt to send as a system message before the user message.'
    required: false
  log_actions_to_issue:
    description: "If true, post the agent's responses to the issue or PR as a comment."
    required: false
    default: 'false'
  mcp_servers:
    description: 'JSON string or file:// path specifying additional MCP server configs to use (optional). Example: |\n  {\n    "time": {\n      "type": "stdio",\n      "command": "docker",\n      "args": ["run", "-i", "--rm", "mcp/time"]\n    }\n  }'
    required: false
  add_label_on_success:
    description: 'Comma-separated list of labels to add to the issue or PR after a successful run.'
    required: false
  remove_label_on_success:
    description: 'Comma-separated list of labels to remove from the issue or PR after a successful run.'
    required: false
  add_label_on_error:
    description: 'Comma-separated list of labels to add to the issue or PR if an error occurs.'
    required: false
  remove_label_on_error:
    description: 'Comma-separated list of labels to remove from the issue or PR if an error occurs.'
    required: false
  mcp_startup_timeout:
    description: 'Timeout in milliseconds to wait for MCP servers to start (default: 10000).'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'zap'
  color: 'blue' 