name: Full Agent Flow

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled, synchronize]
  issue_comment:
    types: [created]

jobs:
  todo_handler:
    name: Todo Issue Handler
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.label.name == 'todo'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Prefetch npx dependencies
        run: |
          npm install -g blevinstein-github-agent @modelcontextprotocol/server-filesystem @cyanheads/git-mcp-server
      - name: Set up Git user for commits
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Run Github Agent for todo issues
        uses: blevinstein/github-agent@main
        with:
          treat_reply_as_comment: true
          remove_label_on_success: todo
          add_label_on_success: evaluate
          remove_label_on_error: todo
          add_label_on_error: input-needed
          instructions: |
            The following issue has been labeled 'todo':
            Repository: {{repository.full_name}}
            Title: {{issue.title}}
            Number: {{issue.number}}
            Body: {{issue.body}}
            Comments: {{issue.comments}} (use the get_issue tool to get more details)
            Your task is to:
            - Attempt to resolve the issue, either by providing a direct answer, research, or by creating a pull request that addresses the issue.
            - If you create a PR, reference the issue number in the PR description.
            - If the task cannot be completed, or if it requires additional information or input, write a comment to that effect.

            # TODO: Add any project-specific context or instructions for the agent here.
          model: anthropic/claude-3.7-sonnet

  evaluate_handler:
    name: Evaluate Issue/PR Handler
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.label.name == 'evaluate'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Prefetch npx dependencies
        run: |
          npm install -g blevinstein-github-agent @modelcontextprotocol/server-filesystem @cyanheads/git-mcp-server
      - name: Set up Git user for commits
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Run Github Agent for evaluation
        uses: blevinstein/github-agent@main
        with:
          treat_reply_as_comment: true
          remove_label_on_success: evaluate
          remove_label_on_error: evaluate
          add_label_on_error: input-needed
          instructions: |
            The following issue or PR has been labeled 'evaluate':
            Repository: {{repository.full_name}}
            Title: {{issue.title}}
            Number: {{issue.number}}
            Body: {{issue.body}}
            Comments: {{issue.comments}} (use the get_issue tool to get more details)
            Your task is to:
            - Review the work performed on this issue or PR.
            - If the task is complete, label as 'complete'.
            - If the task is incomplete but can be iterated on with simple tweaks, add a comment explaining what is missing and label as 'todo'.
            - If more human input or review is needed, label as 'input-needed' and assign an appropriate reviewer.
            - Use your best judgment to determine the correct course of action.

            # TODO: List reviewers to assign for 'input-needed', and any additional evaluation criteria.
          model: anthropic/claude-3.7-sonnet

  pr_comment_handler:
    name: PR Comment Handler
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'github-agent')
    permissions:
      contents: write
      issues: write
      pull-requests: write
    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Prefetch npx dependencies
        run: |
          npm install -g blevinstein-github-agent @modelcontextprotocol/server-filesystem @cyanheads/git-mcp-server
      - name: Set up Git user for commits
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Run Github Agent for comments on LLM-created PRs
        uses: blevinstein/github-agent@main
        with:
          treat_reply_as_comment: true
          instructions: |
            A new comment was posted on a pull request created by the agent:
            Repository: {{repository.full_name}}
            PR Title: {{issue.title}}
            PR Number: {{issue.number}}
            Comment Author: {{comment.user.login}}
            Comment Body: {{comment.body}}
            Please update the PR or respond to the comment as appropriate, referencing the PR number in your response.
          model: anthropic/claude-3.7-sonnet
