name: Github Agent

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled, synchronize]
  issue_comment:
    types: [created]

jobs:
  fixme:
    name: Fixme Issue Handler
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.label.name == 'fixme'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git user for commits
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Run Github Agent for fixme issues
        uses: blevinstein/github-agent@main
        with:
          treat_reply_as_comment: true
          instructions: |
            The following issue has been labeled 'fixme':
            Title: {{issue.title}}
            Number: {{issue.number}}
            Body: {{issue.body}}
            More details are available using the get_issue tool.
            Please propose a fix for this issue. If possible, create a pull request that resolves it and reference the issue number in the PR description.
          model: anthropic/claude-3.7-sonnet

  reviewme:
    name: Reviewme PR Handler
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.label.name == 'reviewme'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git user for commits
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Run Github Agent for reviewme PRs
        uses: blevinstein/github-agent@main
        with:
          treat_reply_as_comment: true
          instructions: |
            The following pull request has been labeled 'reviewme':
            Title: {{pull_request.title}}
            Number: {{pull_request.number}}
            Body: {{pull_request.body}}
            More details are available using the get_pull_request tool.
            Please review the code changes in this PR. If appropriate, run tests, and leave a review or comments with your feedback and suggestions.
          model: anthropic/claude-3.7-sonnet

  pr_comment:
    name: PR Comment Handler
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'github-agent')
    permissions:
      contents: write
      issues: write
      pull-requests: write
    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git user for commits
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Run Github Agent for comments on LLM-created PRs
        uses: blevinstein/github-agent@main
        with:
          treat_reply_as_comment: true
          instructions: |
            A new comment was posted on a pull request created by the agent:
            PR Title: {{issue.title}}
            PR Number: {{issue.number}}
            Comment Author: {{comment.user.login}}
            Comment Body: {{comment.body}}
            More details are available using the get_pull_request tool.
            Please update the PR or respond to the comment as appropriate, referencing the PR number in your response.
          model: anthropic/claude-3.7-sonnet

  lookup:
    name: Wikipedia Lookup Handler
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.label.name == 'lookup'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git user for commits
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Run Github Agent with Wikipedia MCP
        uses: blevinstein/github-agent@main
        with:
          treat_reply_as_comment: true
          instructions: |
            The following issue has been labeled 'lookup':
            Title: {{issue.title}}
            Number: {{issue.number}}
            Body: {{issue.body}}
            More details are available using the get_issue tool.
            Please post a comment on this issue with the answer to any knowledge questions in the issue.
          model: anthropic/claude-3.7-sonnet
          mcp_servers: |
            {
              "wikipedia-mcp": {
                "command": "docker",
                "args": [
                  "run",
                  "-i",
                  "--rm",
                  "mcp/wikipedia-mcp"
                ]
              }
            }